--- 
engines: 
  csslint: 
    enabled: true
  duplication: 
    config: 
      languages: 
        - javascript
    enabled: true
  eslint: 
    enabled: true
  fixme: 
    enabled: true
exclude_paths: 
  - docs/
